### ISSUE TITLE
Gnus message buffer: org-mime-htmlize not converting windows share properly

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#100]
Emacs 25.1 on Gnu/Linux 16.04. If I compose a Gnus message with a windows share, the org-mime-htmlize is not converting it properly.

Original message
```
\\mymachine\my\shared\location
```
After `org-mime-htmlize` (note that the HTML part has consumed the entire shared location string)
```
<#multipart type=alternative><#part type=text/plain>#+OPTIONS: latex:t toc:nil H:3
\\mymachine\my\shared\location
<#multipart type=related><#part type=text/html><p>
\<br  />
</p>
<#/multipart>
<#/multipart>
```

Escaping the `\` with `\` prints the forward slash but doesn't print the string after it in HTML message. Also it puts extra \ characters in plain text message part

E.g. original message,
```
\\\\mymachine\\my\\shared\\location
```
After `org-mime-htmlize`
```
<#multipart type=alternative><#part type=text/plain>#+OPTIONS: latex:t toc:nil H:3
\\\\mymachine\\my\\shared\\location
<#multipart type=related><#part type=text/html><p>
\\\\\\<br  />
</p>
<#/multipart>
<#/multipart>

```

**Comment by redguardtoo** [comment]
Have your try it embed link as code snippet, like `=this-is-link=`, Please note org-mime just use standard org export commands. Check org manual on how to export link, there might exist better ways.

**Comment by amittendulkar** [comment]
Thanks. Using the code snippet format works. Closing the issue.
