### ISSUE TITLE
C-x b is not showing the pipe separated recent buffers list

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#101]
After getting latest .emacs.d, I have noticed that while switching buffers `C-x b` I no longer see the recently accessed buffers (pipe separated list) in the bottom area. It seems the support has somehow broken. I have to press TAB to see the list of buffers in the expanded area.

My emacs switched back to Emacs 24.5.1 (from 25.1) after I did apt-get update on my Ubuntu 16.04 system.

**Comment by redguardtoo** [comment]
d92d362 use ivy-switch-buffer (Chen Bin)

You can simply `(ivy-mode 1)` in `~/.custom.el` to enable all the handy tools from ivy.

**Comment by amittendulkar** [comment]
Thanks, working for me now.
