### ISSUE TITLE
直接clone 到.emacs.d,启动不了

### ISSUE THREAD

**Issue by Young-people** [redguardtoo/mastering-emacs-in-one-year-guide#102]
一直在Contacting host,是因为配置不对吗~
我再一年成为Emacs高手的仓库和这个仓库都没有找到如何配置，现在直接clone下来启动不了~
求指点，怎么应用这个仓库的配置，并让我的emacs工作起来~
顺便收一句，emcas网站没找到推荐的24.3,24.4的下载，brew也没找到旧版本，是我的操作方式有误吗？现在是 brew install --with-cocoa 安装，mac系统。
额，我在组织完语言吧这行字打上的时候发现emacs启动了。

**Comment by Young-people** [comment]
Warning (bytecomp): ‘mapcar’ called for effect; use ‘mapc’ or ‘dolist’ instead [11 times]
Warning (bytecomp): ‘interactive-p’ is an obsolete function (as of 23.2); use ‘called-interactively-p’ instead.
Warning (bytecomp): the function ‘pyim-permutate-list’ is not known to be defined.
Warning (bytecomp): the function ‘evil-normal-state-p’ is not known to be defined.
Warning (bytecomp): function ‘mapcan’ from cl package called at runtime

**Comment by Young-people** [comment]
idle-require: require init-hs-minor-mode
idle-require: require init-writting
idle-require: require init-pomodoro
idle-require: require init-artbollocks-mode
idle-require: require init-semantic
idle-require finished
<nil> <down-mouse-1> is undefined
<nil> <mouse-1> is undefined

**Comment by Young-people** [comment]
其实我挺想直接拿高手的来用的~，上面是启动界面的 Messages

**Comment by redguardtoo** [comment]
Looks setup is fine. Maybe it's network problem. Either setup your proxy or use workaround in READ (search "stable")

**Comment by superewe** [comment]
@Young-people  国内无法直接访问elpa的官方源，使用清华的软件源

diff --git a/lisp/init-elpa.el b/lisp/init-elpa.el
index ece6bc0a..bd6966c6 100644
--- a/lisp/init-elpa.el
+++ b/lisp/init-elpa.el
@@ -71,8 +71,8 @@ But you may use safer HTTPS instead.")
         ;; ("org" . "http://orgmode.org/elpa/") ; latest org-mode
         ("localelpa" . "~/.emacs.d/localelpa/")
         ("my-js2-mode" . "https://raw.githubusercontent.com/redguardtoo/js2-mode/release/")
-        ("melpa" . "https://melpa.org/packages/")
-        ("melpa-stable" . "https://stable.melpa.org/packages/")))
+        ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
+        ("melpa-stable" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa-stable/")))

 ;; Un-comment below line if your extract https://github.com/redguardtoo/myelpa/archive/master.zip into ~/myelpa/
 ;; (setq package-archives '(("myelpa" . "~/myelpa")))
