### ISSUE TITLE
not consistent between emacs.d/init-gnus and .gnus

### ISSUE THREAD

**Issue by songpeng** [redguardtoo/mastering-emacs-in-one-year-guide#103]
Hi, 
Thanks a lot for the great gnus article.
I notice that `.gnus` is not consistent with your `emacs.d/init-gnus.el`.
For example, 
1. you have `extract email address function` in init-gnus.el, but not mentioned in the article.
2. both of .gnus and init-gnus contain short-key "o" for the same function.

Could you please provide a complete one in this article? 
BTW, the binding-keys in hydra is great! 

Songpeng

**Comment by redguardtoo** [comment]
`init-gnus.el` can be ignored. it's the default setup I'm sharing. It's not complete, it's not usable without setup in `.gnus.el`.

The `.gnus.el` will override `init-gnus.el`. It can start gnus without `init-gnus.el`.

**Comment by songpeng** [comment]
got it~
