### ISSUE TITLE
evil-mode 链接失效

### ISSUE THREAD

**Issue by BenjaminCHP** [redguardtoo/mastering-emacs-in-one-year-guide#104]
guide_zh.org文件中第三方插件一章中的表格内evil链接失效

**Comment by asvcer** [comment]
You can use a proxy or change a mirror repo url.

**Comment by vipzrx** [comment]
@asvcer 
      '(;; uncomment below line if you need use GNU ELPA
        ;; ("gnu" . "https://elpa.gnu.org/packages/")
        ;; ("org" . "http://orgmode.org/elpa/") ; latest org-mode
        ("localelpa" . "~/.emacs.d/localelpa/")
        ("my-js2-mode" . "https://raw.githubusercontent.com/redguardtoo/js2-mode/release/")
        ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
        ("melpa-stable" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa-stable/")))
