### ISSUE TITLE
Suggested to include gnus-icalendar appointment import functionality in the document

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#106]
I found this really good built-in functionality. You need to add the following in `.gnus.el`
```
(require 'gnus-icalendar)
(gnus-icalendar-setup)

(setq gnus-icalendar-org-capture-file "~/Documents/agenda.org")
(setq gnus-icalendar-org-capture-headline '("Calendar")) ;;make sure to create Calendar heading first
(gnus-icalendar-org-setup)
```

The above will start showing appointments sent by others (e.g. Outlook meeting requests) in message buffer.

You can press `i e` to export appointment to your org file (will start showing up appointment in agenda buffer). You can also accept (`i a`)/tentative (`i t`)/decline (`i d`) the request. It will accordingly send the response through Gnus. Check agenda (`i c`) will open up agenda to check whether the appointment timing works before exporting to Org file.

**Comment by amittendulkar** [comment]
One above code opens up another issue. I am no longer able to use org-capture to quickly create the tasks (`C-c c` followed by `t`). I haven't yet got into lisp. Any suggestions as to how to keep the earlier template structure impact and also include the above code (append to existing templates or something)?

**Comment by redguardtoo** [comment]
I'm not sure about including this. It has not been updated for three years. Usually I use web app or Outlook to set the event and use my phone to view the calendar, so I don't need org-icalendar.
