### ISSUE TITLE
insert-mode 下如何选择 <Leader>

### ISSUE THREAD

**Issue by zhujinxuan** [redguardtoo/mastering-emacs-in-one-year-guide#110]
非常感谢此文的写作，这让我这个几年前从 emacs 转为 vim 的想转 spacemacs 了；

但是文中这一段我有些不是很明白

> Vim 自带 Leader 键的功能, 你先按了 Leader 键 (很多人定义为空格键) 后, 再按其他键 (比如 kk) 会触发你自定义的命令. 本质就是给你更多的快捷键.

主要是这样一点，很多时候有些和 leader 绑定的操作是在 insert-mode 下进行的，比如 emmet-vim 的展开；这时候把 <Leader> 总绑在 space 上可能不是一个很好的选择。

不过我现在也找不到同时能够适用于 normal 和 insert 的 leader，我现在是把 normal 的 leader 绑在 hjkl 的 l 上，然后 insert 绑在 comma 上（因为编程和写文的时候我一般 comma 后接空格或者换行所以不用担心冲突

不知道您是否有更好的 leader 绑定选择？

**Comment by redguardtoo** [comment]
You surely can bind certain key sequences to some commands. I have no such setup in insert-mode. 
The only exception is `kj` is used to escape from insert mode. That's setup from package `evil-escape`
