### ISSUE TITLE
想使用Steve Purcell的配置写Lisp，但是Slime无法启动，请问知道怎么回事吗？

### ISSUE THREAD

**Issue by ZhuJiayou** [redguardtoo/mastering-emacs-in-one-year-guide#111]

**Comment by redguardtoo** [comment]
一般都是环境变量PATH没设置，建议你把我的文章仔细读一遍：

**掌握基本知识, 什么是环境变量 (比如 PATH, HOME 之类的变量), 什么是 stdin, stdout, pipe**

**Comment by ZhuJiayou** [comment]
我知道你不用Slime，才没说的很细。
只是简单提一下，你以为我只问你一个人啊？
你应该去看一下“怎样与人交流”以及“如何控制狂妄”。

**Comment by redguardtoo** [comment]
你过于敏感了。这是我对新手的标准回答。我时间有限，所以只能拣要点讲一下。

因为我订阅了Purcell的消息，所以你同时问purcell的同样问题也出现在我的时间线上，

第一，同一问题同时问不同的人是很不恰当的，如果每个人都这样做，github上要充满了重复的消息

第二，在pucell的时间线上你提供的信息也不够具体，但我可以看出你是新手。也许你是天才，是我不识才。但如前所说，我时间有限，回答一律从简，所以语气上可能你觉得有所冒犯，只能请你多体谅了。
