### ISSUE TITLE
package "async" is not avaiable for installation in Win7

### ISSUE THREAD

**Issue by gehancoder** [redguardtoo/mastering-emacs-in-one-year-guide#113]
Hi, I have installed emacs24.3 in Win7 OS. And then i setup emacs follow your readme, download zip file and exact to path "C:\Users\32135\Documents" which is my HOME path. But when i launch emacs, it got error message (copy them as below): Then i comment `(require-package 'async)` in C:\Users\32135\Documents\.emacs.d\lisp\init-elpa.el file, but got emacs same error for next package dash and so on.
 **Warning (initialization): An error occurred while loading `c:/Users/32135/Documents/.emacs.d/init.el':

error: Package `async' is not available for installation

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.**

**Comment by redguardtoo** [comment]
Maybe it's network problem I got same issue a few days ago. But now Emacs 24.3 is working.

**Comment by gehancoder** [comment]
Hi @redguardtoo , I also have a try with the stable version but got same error message. I download 2 zip file and extract both them into path "C:\Users\32135\Documents" which is my HOME path, and then i add code `(setq package-archives '(("myelpa" . "~\myelpa")))` or `(setq package-archives '(("myelpa" . "~\\myelpa")))` in the head of init-elpa.el file.

**Comment by gehancoder** [comment]
Hi, now i upgrade emacs to version 25.3, it also got same error message with online and stable configuration. By the way, i have a VPN and access google or other foreign websites.

**Comment by redguardtoo** [comment]
See `If you use Windows Emacs, you have to install GnuTLS Dlls manually to be able to install packages from remote repositories` on README

**Comment by gehancoder** [comment]
Hi @redguardtoo, thanks for your great help. Now my Emacs is ok and the reason is i am not careful and did not install GnuTLS Dlls.
