### ISSUE TITLE
Why can't I set my configuration LC_MESSAGES in locale to en_US.UTF-8

### ISSUE THREAD

**Issue by lmxyy** [redguardtoo/mastering-emacs-in-one-year-guide#114]
I followed your suggestion in the email to set the LC_MESSAGES to en_US.UTF-8, but I always failed.
This is my locale setup.
```
~$ locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en_AU:en_CA:en_GB:en_US:en
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

And when I use the command ```~$sudo update-locale LC_MESSAGES=en_US.UTF-8```, the terminal always tells me ```*** update-locale: Warning: LANGUAGE ("zh_CN:en_AU:en_CA:en_GB:en_US:en") is not compatible with LC_MESSAGES (en_US.UTF-8). Disabling it.``` And if I use ```~$sudo emacs /etc/default/locale``` and add ```LC_MESSAGES=en_US.UTF-8``` in the end of the file, it doesn't work too, no matter how many times I reboot the system. I have no idea what the problem is.

The text in /etc/default/locale originly was

```
#  File generated by update-locale
LANGUAGE="zh_CN:en_AU:en_CA:en_GB:en_US:en"
LANG=zh_CN.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8
```
At first, I turned to [askubuntu.com](), but I couldn't see the CAPTCHA due to GFW. And as you know, because of The 19th National Congress of CPC, my SS was broken. So I could only resort to you. 
Thanks for your kind help.

**Comment by redguardtoo** [comment]
you don't need setup LANGUAGE and LANG
