### ISSUE TITLE
Not a bug, just some questions to ask, Thanks

### ISSUE THREAD

**Issue by gehancoder** [redguardtoo/mastering-emacs-in-one-year-guide#115]
Hi, i add some setup about highlight parentheses and latex edit&preview base on your configuration, but it did not work on after I installed the package I need except I execute command with "M-X" key. But i want to make my setup work on by default when start emacs, not to make it work manually. Below are my changes:

1. I added 2 lines in the **init.el** file, `(require 'init-setup)` `(require 'init-latex)`.

2. I create 2 files named **init-setup.el** and **init-latex.el** under folder _.emacs.d/lisp/_. In these 2 files, even I delete code written by myself and just keep the most simple code copy from Internet, it still not work on. For example, the contents in **init-latex.el** file:
```
(latex-preview-pane-enable)
(setq latex-preview-pane-mode t)

(provid 'init-latex)
```

**Comment by redguardtoo** [comment]
the last line has typo

**Comment by gehancoder** [comment]
sorry, just typo in here, it is correct in file like `(provide 'init-latex)`.

**init-setup.el** contents copy from [https://www.emacswiki.org/emacs/HighlightParentheses](url)
```
(define-globalized-minor-mode global-highlight-parentheses-mode
  highlight-parentheses-mode
  (lambda ()
    (highlight-parentheses-mode t)))
(global-highlight-parentheses-mode t)
```

**Comment by redguardtoo** [comment]
you also need install corresponding packages through melpa.

**Comment by gehancoder** [comment]
yes, i already installed them by **M-x package-install**. And there is something strange when i put `(require 'init-setup) (require 'init-latex)` in different location in **init.el** file. When i put them before `(require 'init-autoload)` and it will make your setup not work on. So i append them after `(require 'init-hydra)`, but it did not work on by default when i start emacs. Except it will be useful after i execute **M-X highlight-parentheses-mode** and **M-x latex-preview-pane-mode** manually.

**Comment by gehancoder** [comment]
I am very sorry for wasting your time. It's my mistake it has a typo in my **init-setup.el** file, now the highlight parentheses feature is ok. I am feel so sorry for wasting your time. Please forgive me. Thanks for your help.

**BUT** it still has a little issue for latex preview as pdf, it only can displays the first page in the right part window of emacs, it can't displays other page (e.g. a pdf file with 10 pages). I will google it once i am free and will close this issue after i resolve it. Thank you again.
