### ISSUE TITLE
A question to ask (irony-mode)

### ISSUE THREAD

**Issue by yoacompsci** [redguardtoo/mastering-emacs-in-one-year-guide#116]
Hello Chen, first of all thanks for your repo. It's fantastic.
I am working with your `.emacs.d` configuration in addition with the irony-mode for code completion in C++. Everything works fine, I open C++ files and activating irony-mode in the current buffer, typing `M-x` `irony-mode` `RET`, I got the completions at point properly. The issue is that I would like to auto-activate the irony-mode in every buffer that is C++ file automatically. To do that I have included this commands in the init file: 
`(add-hook 'c++-mode-hook 'irony-mode) 
(add-hook 'c-mode-hook 'irony-mode) 
(add-hook 'objc-mode-hook 'irony-mode)`
But didn’t work, each time that I open new C++ file it's not the irony-mode activated and need to be activated manually by corresponding command, that is: `M-x` `irony-mode` `RET.`
I have checked this feature in a basic setup (default plus irony-mode add-on’s) and Works properly, that is, every new buffer as C++ file opened, the irony-mode is automatically activated.
Any idea why this feature doesn’t fit in the “.emacs.d” configuration? Or what I’m doing wrong ?
Many thanks !!!

**Comment by redguardtoo** [comment]
I tested with your setup and it's fine. At least `irony-mode` is loaded (You can `C-h m` and search Irony to verify).

I don't know much about `irony` but seems the developer of `irony-mode` suggests `company-irony` for auto-completion. Check https://github.com/Sarcasm/irony-mode/issues/331

**Comment by yoacompsci** [comment]
Hello Chen, 
Solved the problem. It was due to I've overriden the `'c-mode-common-hook` against the defined in the `init-cc-mode.el` file. Now works properly the autocompletion with irony-mode. 

Thanks again!!!
