### ISSUE TITLE
paste-from-x-clipboard error

### ISSUE THREAD

**Issue by shyung** [redguardtoo/mastering-emacs-in-one-year-guide#118]
When I try to paste with ``,zz``, it comes following:
```
usr/bin/xsel: Can't open display: (null)
: Inappropriate ioctl for device
```
I have no idea what it means.  
I just wonder the reason and how to copy/paste successfully.
Thanks for your help.

**Comment by redguardtoo** [comment]
Run `ssh -X -C -c blowfish-cbc,arcfour $@` instead of simply `ssh`, see https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely

**Comment by shyung** [comment]
I guess I catch your point. In order to use those servers in my lab, I need to ssh to them by using Xshell on my desktop which OS is windows. I made it with the "Xshell+Xmanager" solution. Thanks for your help again.

**Comment by redguardtoo** [comment]
I solved this problem by swtiching to `xclip.el`
