### ISSUE TITLE
emacs 好用的collapse插件推荐

### ISSUE THREAD

**Issue by yu-yuxuan** [redguardtoo/mastering-emacs-in-one-year-guide#123]
我目前在用hs hs-hide-all 和 hs-show-all, 但无法做到像visual studio 那样分块折叠，
 hs-hide-all 通常会把所有函数全部折叠到一块。有没有好的collapse插件推荐，谢谢

**Comment by redguardtoo** [comment]
I don't use collapse. 

I usually just jump between matching tags, using `evil-matchit`

**Comment by yu-yuxuan** [comment]
@redguardtoo Thank you very much. I am now trying this extension
