### ISSUE TITLE
Java后端有推荐的emacsd配置吗

### ISSUE THREAD

**Issue by weidongcao** [redguardtoo/mastering-emacs-in-one-year-guide#127]
大神您好,我是做大数据的,主要使用Java,Python,Shell,Linux进行开发,有推荐的emacsd配置吗?purcell大神的配置我看了,没有针对Java进行定制

**Comment by redguardtoo** [comment]
I recommend counsel-gtags and company-gtags. Fast and efficient. You may lose a little precision but that's trivial.
