### ISSUE TITLE
emacs卡住

### ISSUE THREAD

**Issue by HelloYJohn** [redguardtoo/mastering-emacs-in-one-year-guide#132]
当我用emacs打开一个c++项目的文件，光标放在函数上面，按下Ctrl + ], emacs 会自动帮我grep 使用该函数的所有索引，但是我去C-x C-c 去关闭emacs时,
emacs 卡住了，显示的信息 Wrote /User/john-y/.emace.d/.session，而且各种关闭都不好使，虽然可以C-g 回到正常，但是emacs 无法关闭，请问有什么
方式可以解决这个问题，或者不去保存.session
                                                                                                                                            感谢

**Comment by redguardtoo** [comment]
Need more information. OS, emacs version. your setup. exact step to reproduce issue.

`C-]` triggers `counsel-etags-find-tag-at-point`. Global variables are saved by `session-save-session`. You also need manullay run this command at least once because I'm sure whether it will suspend emacs.

**Comment by redguardtoo** [comment]
It seems session save is fine.

`counsel-etags` will automatically run `ctags` to scan code when you save changes.

What's message of `ctags --help`?

**Comment by HelloYJohn** [comment]
Thanks for your help! I think I can do it.
