### ISSUE TITLE
Illusory claims of practicality

### ISSUE THREAD

**Issue by dickmao** [redguardtoo/mastering-emacs-in-one-year-guide#137]
The "practical guide" gives the illusion that GNUS is easy by glossing over the setup and jumping right into the "essential 5%" of the UI.  The UI, while counter-intuitive, is not the hard part.  Setup is everything.

> Gnus is **solid**

GNUS began as a newsreader and overextended this abstraction to accommodate complex mail protocols.  Such extension generally results in fragile code.  The code's abundant matching on hardcoded regular expressions do not engender confidence.  I'm sure Mr. Ingebrigtsen's present self would not have written the GNUS code the way his much younger self did.

The do-one-thing-and-do-it-well approach needs to apply to something as terrible as mail.  It is far easier to troubleshoot mail from small command-line clients such as mutt and notmuch than the vagaries of the emacs editor.  Because GNUS tries to cover the entire pipeline of retrieval and presentation (while also maintaining the abstraction of newsreading), it is destined to never reach widespread adoption, even if rewritten.

**Comment by redguardtoo** [comment]
Gnus is good after customization. I've already solved all the major problems of Gnus.

Gnus is part of Emacs, so combining the power of other plugins (yasnippet, avy, company-mode ...), it could be the best email client in the world.
