### ISSUE TITLE
emacs里有没有px自动转换vw、vh的插件？

### ISSUE THREAD

**Issue by qdhaiqiang** [redguardtoo/mastering-emacs-in-one-year-guide#142]
哈喽，陈大神：
emacs写clojurescript的css时，有没有插件能将px这种尺度，自动换算成vw、vh的插件，类似vs code的插件[px-to-vw](https://github.com/usecodelee/px-to-vw)。

**Comment by qdhaiqiang** [comment]
有一个[postcss-px-to-viewport](https://github.com/evrone/postcss-px-to-viewport)插件，但是我们的项目时clojurescript，用shadow-cljs 编译的，不知道怎么用这个插件，因此问下emacs这个ide有没有能力。

非常感谢

**Comment by redguardtoo** [comment]
Technically it's easy. The key algorithm is  `px * 100)/ viewportWidth` to get vw.  It's pretty simple for Emacs lisp.

**Comment by qdhaiqiang** [comment]
Thanks a lot.

**Comment by qdhaiqiang** [comment]
幸亏我能用中文表述。我是想这样，假设我的viewportWidth是1366，从设计图上只能看到设计给的单位是px，比如一个div是200px，我们用emacs开发自适应页面，写css是希望写20px保存时自己换算成(200*100/1366)14.64pw

源代码：
.div-class{
   width: 200px;
}
保存，或者有其他快捷键后
.div-class{
   width：14.64pw;
}

这个过程能自动化些。

**Comment by redguardtoo** [comment]
技术上没有问题，你可以试着写一下，一天足够el。emacs的api比vscode要丰富。有问题到emacs-china上问一下。我比较忙，如果不是我感兴趣的项目就不太可能写了。

**Comment by qdhaiqiang** [comment]
明白，非常感谢，如果我能有能力写出来的话，我会在这个issue上再跟进回复。
感谢大神百忙之中的回复。

**Comment by qdhaiqiang** [comment]
今天搞出来一个，确实花了小一天的精力，非常感谢大神的鼓励。

[px2vw-emacs-plugin](https://github.com/qdhaiqiang/emcas-plugin-px2vw)
