### ISSUE TITLE
Purcell的配置与spacemacs如何选择？

### ISSUE THREAD

**Issue by sharefantasy** [redguardtoo/mastering-emacs-in-one-year-guide#143]
你好，我从Jetbrains的ide切换到spacevim，又从spacevim切换到spacemacs，还不足1个月. 想请问，如果以深入在工作中逐步切换编辑器的目的来说，直接使用Purcell的配置好，还是继续使用spacemacs比较好？

**Comment by redguardtoo** [comment]
取决于你的偏好，两者都可以，
spacemacs  支持的编辑语言多，基本的设置都帮你大包大揽了。
purcell 支持他自己用的语言，没有过多的定制。

我个人是一直用purcell的，因为我比较懒又个人想法比较多，会有大量修改原始配置的冲动，用spacemacs的话我工作量比较大。

实际上用哪个配置都是小节，关键是掌握文本文件操作术

**Comment by sharefantasy** [comment]
好的，我需要用go，还是用spacemacs吧。你的文章很有启发性，读罢获益良多，感谢。:)
