### ISSUE TITLE
Bitbucket的issue链接已经失效

### ISSUE THREAD

**Issue by Gaeric** [redguardtoo/mastering-emacs-in-one-year-guide#147]
** Evil 和 Emacs 原生插件的兼容性 这一节下
链接: https://bitbucket.org/lyro/evil/issue/511/let-certain-minor-modes-key-bindings 因为Bitbucket的仓库关闭已无法链接，无法看到其内容；
github上有转录issue的内容：https://github.com/emacs-evil/evil/issues/511
是否考虑将链接更新？

**Comment by redguardtoo** [comment]
c4aa6df update evil link (Chen Bin)
