### ISSUE TITLE
Gnus tip suggestion: auto change smtp cryption method (smtpmail-stream-type) for different smtp server

### ISSUE THREAD

**Issue by pRot0ta1p** [redguardtoo/mastering-emacs-in-one-year-guide#149]
First, use gnus-parameters to override the user-mail-address variable for different mail accounts, like
```Emacs-Lisp
(setq gnus-parameters
	  '(("mail1"
		 (posting-style
		  (address "mail1@server1")
		  ("X-Message-SMTP-Method" "smtp server1 587")))
		("mail2"
		 (posting-style
		  (address "mail2@server2")
		  ("X-Message-SMTP-Method" "smtp server2 587")))
		("mail3"
		 (posting-style
		  (address "mail3@server3")
		  ("X-Message-SMTP-Method" "smtp server3 465"))))
```
Then, put this piece of code somewhere in your config
```Emacs-Lisp
(defun change-stream-type ()
  (cond ((equal user-mail-address "mail1@server1")
		 (setq smtpmail-stream-type 'ssl))
		((equal user-mail-address "mail1@server2")
		 (setq smtpmail-stream-type 'ssl))
		((equal user-mail-address "mail1@server3")
		 (setq smtpmail-stream-type 'starttls))))
(add-hook 'message-send-hook 'change-stream-type)
```
Then, when compose mail, enter gnus topic view, put cursor on the group that belongs to the mail account you want to send mail with, then run this function or map it to a key:
```Emacs-Lisp
    (defun group-send-mail-from-point ()
        (interactive)
        (gnus-group-mail 2))
```
When you send the mail, smtpmail-stream-type should change according to the function change-stream-type.

I haven't find a way to do this kind thing without writing a function myself, if there are any please tell me.

**Comment by redguardtoo** [comment]
Thanks. It's a cool trick, I will add a section on it.

**Comment by redguardtoo** [comment]
89cc8b3 add smtpmail-stream-type tip (Chen Bin)
