### ISSUE TITLE
Twitter advanced search

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/mastering-emacs-in-one-year-guide#150]
Using https://twitter.com/search-advanced to specify language, I bet `emacs lang:en` is the right syntax. `emacs en` get many Spanish results like

> en /g/? ahi hablamos de vim contra emacs lains y demas— qorg11&lambda;

> En buena hora que aprendí las funciones básicas de Emacs.

**Comment by redguardtoo** [comment]
5f88b4d twitter tip (Chen Bin)
