### ISSUE TITLE
请教一个关于 macro 的问题

### ISSUE THREAD

**Issue by loyalpartner** [redguardtoo/mastering-emacs-in-one-year-guide#152]
在 vim 里面，我录制了一个宏存储到寄存器 `a`, 宏的内容是 `ohello^[`,
就是打开一行，输入 `hello` 然后回到 normal 模式。
如果我要修改这个宏，我会 `“ap` 粘贴寄存器的内容，再修改为
`ohello word^[`，然后 `^"ay$` 复制修改的内容到寄存器 `a`。
这时候 `@a` 会打开一行 输入 `hello world`.

在 evil 里面，我用同样方式，修改的宏会卡到 insert 模式，回不到 normal 模式。

想问下斌神有没有遇到这个问题，或者有没有更好的办法修改宏

**Comment by redguardtoo** [comment]
这个你给evil报告个bug吧。

我不用macro，一般都是直接写lisp 代码。`(evil-normal-state)`应该是回到normal状态

**Comment by loyalpartner** [comment]
好的
