### ISSUE TITLE
hunspelldict　保存文件会提示错误是什么原因？

### ISSUE THREAD

**Issue by bensonlew** [redguardtoo/mastering-emacs-in-one-year-guide#153]
Wrote /home/liubinxu/.emacs.d/custom.el
defun: (NAME ARGLIST &optional DOCSTRING DECL &rest BODY)
Mark activated

Wrote /home/liubinxu/.emacs.d/custom.el
defun: (NAME ARGLIST &optional DOCSTRING DECL &rest BODY)
Error running timer ‘auto-save-buffers’: (wrong-type-argument stringp nil)
Saving file /home/liubinxu/.emacs.d/custom.el...
Wrote /home/liubinxu/.emacs.d/custom.el
Starting new Ispell process hunspell with hunspelldict dictionary...
ispell-parse-hunspell-affix-file: ispell-phaf: No matching entry for hunspelldict in ‘ispell-hunspell-dict-paths-alist’.

**Comment by redguardtoo** [comment]
What's the value of `ispell-program-name`?

**Comment by bensonlew** [comment]
> What's the value of `ispell-program-name`? What's your Emacs version?
ispell-program-name  hunspell
GNU Emacs 25.3.1

**Comment by bensonlew** [comment]
找到解决方法了在这个文件里
~/.emacs.d/lisp/init-spelling.el

;; Hunspell Setup:
;; 1. Install hunspell from http://hunspell.sourceforge.net/
;;
;; 2. Download openoffice dictionary extension from
;; http://extensions.openoffice.org/en/project/english-dictionaries-apache-openoffice
;;
;; 3. Say `dict-en.oxt' is downloaded. Rename it to `dict-en.zip' and unzip
;; the contents to a temporary folder. Got "en_US.dic" and "en_US.aff" in
;; that folder.
;;
;; 4. Hunspell's option "-d en_US" means finding dictionary "en_US"
;; Set `ispell-local-dictionary-alist' to set that option of hunspell
;;
;; 5. Copy "en_US.dic" and "en_US.aff" from that temporary folder to
;; the place for dictionary files. I use "~/usr_local/share/hunspell/".
;;
;; 6. Add that folder to shell environment variable "DICPATH"
;;
;; 7. Restart emacs so when hunspell is run by ispell/flyspell to make
;; DICPATH take effect
;;
;; hunspell searches a dictionary named "en_US" in the path specified by
;; `$DICPATH' by default.
