### ISSUE TITLE
replacement for highlight-symbol

### ISSUE THREAD

**Issue by phye** [redguardtoo/mastering-emacs-in-one-year-guide#154]
Noticed that you've recently removed highlight-symbol package in 291170, would like to know if you find better alternatives or simply because you don't use it anymore? 

I'm heavily using it when reading code 😭 to highlight local variables .etc

**Comment by redguardtoo** [comment]
I'm not using highlight symbol. What's your workflow?

**Comment by phye** [comment]
Quite simple, when reading complex functions which may have several key variables, I'm using `highlight-symbol` to hightlight the variable, and then use `highlight-symbol-next` (which I bound to `<comma leader>nn`) and `highlight-symbol-prev` (<comma leader>pp) to jump back and forth. 

Reason for not using simple searching is that you may want to keep multiple variables highlighted so that you can review their relationships more clearly.

**Comment by redguardtoo** [comment]
Make sense.
1fdf2680 Revert "remove highlight-symbol" (Chen Bin)

**Comment by phye** [comment]
Thanks.
