### ISSUE TITLE
`(gnus)` Is it possible to read HTML Articles in an external browser?

### ISSUE THREAD

**Issue by fernandodemorais-jf** [redguardtoo/mastering-emacs-in-one-year-guide#164]
Hello,

Would it be easy to implement the functionality of viewing the local copy of the HTML Article in a browser?

I never used `mu4e`, but it has a builtin "view action" that makes it possible to view the local copy of the HTML email in a browser ([see this link](https://stackoverflow.com/questions/28258133/how-to-view-mu4e-emacs-buffer-in-browser)).

Another interesting thing that people do is to use an external program in conjunction with `mu4e`, like [wkhtmltopdf](https://wkhtmltopdf.org/), to save the HTML email to PDF and view it inside Emacs, with `pdf-tools` maybe ([see this link](https://emacs.stackexchange.com/questions/51180/view-and-save-email-as-pdf)), but I think this is another case for another time :sweat_smile:.

Thanks!

**Comment by redguardtoo** [comment]
sure. It's easy to implement. I will read mu4e's code first.

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/dianyou/commit/2aa1493dc5751b1c1e1d1c8016e98f810372d35f 
![2021-05-26_00-02](https://user-images.githubusercontent.com/184553/119512178-6fa95d00-bdb6-11eb-9c4a-ce82316b8af3.png)

**Comment by fernandodemorais-jf** [comment]
Thank you, @redguardtoo!

It worked like a charm! :1st_place_medal:
