### ISSUE TITLE
打开文件时无法进入vi模式

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/mastering-emacs-in-one-year-guide#48]
打开一个org文件时，会马上进入vi模式；可是打开其它文件，比如s.txt或s.data时，就不会进入vi模式，有时不知道按到什么键，会转到vi模式。本人菜鸟，耽误大神时间，请指点一下。

**Comment by redguardtoo** [comment]
check lisp/init-evil.el, it's my intentional setup. You can modify it.

**Comment by yangdaweihit** [comment]
Thanks, it works!
