### ISSUE TITLE
无意标记了一个色块

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/mastering-emacs-in-one-year-guide#49]
请指教这个色块是什么意思，如何设定并取消。或请给个解决这个问题的线索。耽误您的时间了，谢谢！
![selection_003](https://cloud.githubusercontent.com/assets/10682606/6033173/7197a788-ac4d-11e4-8b13-3df39105bc33.png)

**Comment by redguardtoo** [comment]
It's because  artbollocks-mode's minor bug. 

a53d05a upgrade artbollocks-mode (Chen Bin)
