### ISSUE TITLE
Tramp: Waiting for prompts from remote shell

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/mastering-emacs-in-one-year-guide#50]
For some unknown reason, there is a message read "Tramp: Waiting for prompts from remote shell. " And Emacs stuck there. Why is there this message and could I prohibit these prompt?

**Comment by redguardtoo** [comment]
I rarely use tramp, maybe this one:
http://stackoverflow.com/questions/6954479/emacs-tramp-doesnt-work

**Comment by yangdaweihit** [comment]
the link content hardly understand for me, but I check the buffer listed in Emacs and find out that there is a buffer named "tramp ssh" or something like that. The problem never arise after this buffer being closed.
