### ISSUE TITLE
copy defined multiline text

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/mastering-emacs-in-one-year-guide#51]
Is there some short-cut way in VI mode to copy defined multi-line text like ':2,10 copy' to copy text between row 2 and row 10?

**Comment by redguardtoo** [comment]
not in evil-1.0.9, what's the purpose you need it?

**Comment by yangdaweihit** [comment]
thanks for your respond. I need copy lines between specified rows and the normal ways like Nyy or visual selection by V and y are not so convenient.  Do you have any advice?

**Comment by redguardtoo** [comment]
write your own elisp function (it's pretty simple) or submit bug report at evil's issue tracker https://bitbucket.org/lyro/evil/wiki/Home

**Comment by yangdaweihit** [comment]
ok. I will have a try.
