### ISSUE TITLE
请问如何关闭orgmode中be+动词的词组高亮？

### ISSUE THREAD

**Issue by semimiracle** [redguardtoo/mastering-emacs-in-one-year-guide#52]
请问您知道，如何把orgmode里对be + 动词的词组高亮关闭么？
例如下面的句子中，is conflicted 会被高亮，如附图所示。
JavaScript *is conflicted* about its prototypal nature.

![image](https://cloud.githubusercontent.com/assets/3255399/7100381/29ad0f42-e052-11e4-8fe7-532ab43d9fed.png)

**Comment by redguardtoo** [comment]
comment out `(require 'init-artbollocks-mode)`

**Comment by semimiracle** [comment]
Thanks!
