### ISSUE TITLE
算是对本文一些看法的交流 :)

### ISSUE THREAD

**Issue by hick** [redguardtoo/mastering-emacs-in-one-year-guide#53]
我用词一般比较通俗: 感觉 Emacs 还是只适合比较特定的人群, 那些"懒得折腾不大喜欢玩"也没啥追求和想法的不建议入这个圈, 他们用的结果往往只会传递一些非常糟糕的主观偏颇的判断.

个人感觉最好不要跟那些专业 IDE 较劲,  只针对某个方向比如 c/c++ 开发 GUI, 很多地方专业 IDE 确实不是吃素的,  不过 Emacs 会有它的特色, 不好一一列举.  不管 Emacs 的哲学是不是 living in Emacs , 很多人都是这么玩的 :)

在 Emacs 圈子或者说社区方面, 个人感觉国内氛围比较好而且持久的还是水木社区的 Emacs 版,  链接  http://www.newsmth.net/nForum/#!board/Emacs  .   早前乃至现在很多来这里交流 Emacs 的都是用老式的 telnet bbs 的, 那种字符界面的操作感跟 Emacs 是一样的畅快淋漓.   ace-jump-mode 以及 yasnippet 的原作者早前也都在这里活跃.   另外接触有些人十分喜欢官方列的一些邮件组(Mailing Lists) , http://savannah.gnu.org/mail/?group_id=40  , 我个人更偏爱 reddit:   http://www.reddit.com/r/emacs/

另外对 Emacs/Vim/Sublime Text 在这里发表了些个人, 欢迎拍砖交流 :)  链接  http://emacsist.com/9999

**Comment by redguardtoo** [comment]
C++目前应该非常成熟了,拜托clang和cmake的出现,这个主要不是emacs的功劳.C++我是资深了,这个我是很确定的.

java和C#基本没戏,因为namespace和库的问题太复杂.

我可以考虑把reddit和gnu mailing list加上,reddit实际上和G+完全互相覆盖了,问题是reddit上人的层次比G+要低一点,有很多噪音,所以后来我把reddit去掉了,

但是现在我发觉在国外很多公司G+也是被封掉的,reddit却畅通无阻,而且G+界面做的越来越烂.

水木社区我还不太了解,要评估一下.

**Comment by hick** [comment]
嘿嘿   C/C++ 相关开发我确实倒不熟, 以我理解他们涉及面确实广,  像用来开发 GUI 也有那么大优势?

水木社区质量不一定怎么样, 像精华区等都太老旧了没人整理, 我了解的蛮多人都是从那里开出 Emacs 的萌芽的,  因为以前是清华大学的背景, 除了上面提的几个, 王垠同学等很多国内 Emacs 玩家都曾经活跃于那里. 以前蛮有学院派气质的, 后来慢慢也社会世俗化了.

**Comment by songpeng** [comment]
Hi, redguardtoo,
Thanks for the review on Emacs. It really helps a lot ! And I like the way of your writing. It lets me known how to learn Emacs.
Thanks a lot !
                                       Songpeng
