### ISSUE TITLE
M-x is undefined

### ISSUE THREAD

**Issue by liguangzhou** [redguardtoo/mastering-emacs-in-one-year-guide#54]
when i use the  key M-x , emacs say 'M-x is undefined'    How can i solve it?

I see your blog yesterday ,and a many things i don't understand .  I use your code to build my emacs ,but when i use M-x   ,it says 'M-x is undefined'.   I tried google and baidu  but i can't find any answer, i hope you can help me

**Comment by redguardtoo** [comment]
use my setup, or upgrade to latest evil on melpa-stable

**Comment by liguangzhou** [comment]
yeah , i use your setup.

now i have another question ,when i try to use the gnus to send mail, i use your  ~/.gnus.el  and try to send gmail ,it doesn't work ,then i try someother guy's gnus.el  ,when i use 163mail, the  emacs says  "process smtpmail not running".   i can't find a solution.
i hope you can help!

**Comment by redguardtoo** [comment]
On Tue, May 26, 2015 at 4:13 AM, liguangzhou <notifications@github.com>
wrote:

> .

Check my Gnus guide at, on windows, you need openssh.exe,

https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/gnus-guide-en.org

-- 
help me, help you.
