### ISSUE TITLE
Is there any good tutorial for using el-get?

### ISSUE THREAD

**Issue by tulai** [redguardtoo/mastering-emacs-in-one-year-guide#55]
Hello redguardtoo,
 
Recently, I am trying to use el-get to manage my emacs plugins and my custom settings. My expected way of using el-get are:
1. using el-get to auto install (if not installed) and auto load packages
2. commit all my custom setting (such as shortcuts, themes, fonts) as el files to github as separate repos and install and load them and other social plugins in github automatically
3. for plugin like yasnippets, upload my custom snippets files to git and let el-get automatically install the packages and using my custom snippets

So my ultimate expectation is to use el-get to simplify init.el and make it easier to sync among different computers. It can also avoid gitsubmodule (git in git folder) when backuping all file in the folder .emacs.d to git. I can manage different package in different git repos separately and only clone the init.el file to get all other packages to work.

It seems el-get is designed to manage package in such way (Please correct me if my understanding is wrong.) But there are too few documents for el-get and some examples are ambiguous with few explanations. (http://www.emacswiki.org/emacs/el-get). Maybe this is also because I almost have no knowledge in elisp language. 

Could you tell me whether my expect of using el-get is right? If basically I am right, I hope there will be some doc or tut for dummies like me. I appreciate if you could give some help or suggestion.

**Comment by redguardtoo** [comment]
I recommend `use-package` (http://www.lunaryorn.com/2015/01/06/my-emacs-configuration-with-use-package.html).

It solves the problem I've already solved in a more elegant way. If I have a chance to start from the scratch, I will definitely use `use-packag`.
