### ISSUE TITLE
error: Package `kv-' is unavailable

### ISSUE THREAD

**Issue by MaYingjun** [redguardtoo/mastering-emacs-in-one-year-guide#56]
在 Win7 X64 不联网的电脑上，使用你的emacs.d设置，出现错误如下：
Warning (initialization): An error occurred while loading `c:/Users/xxx/AppData/Roaming/.emacs.d/init.el':

error: Package `kv-' is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

同样的配置，在winxp联网的电脑上不会发生。

**Comment by redguardtoo** [comment]
需要联网,否则就被xp上的`.emacs.d`拷过去

**Comment by MaYingjun** [comment]
不要意思，这几天出差没办法回帖。
的确copy过去就没问题了，看了一下el文件，感觉是编译造成的。
emacs刚刚开始用，但是vlisp已经用了快20年了，希望以后有机会多交流。

**Comment by danyuhao** [comment]
我去， 原来 是这个原因 ，我 大华为 的 内网 限制...

**Comment by Ynjxsjmh** [comment]
`kv` is only available on [kv - MELPA](https://melpa.org/#/kv), so it should be added to [`melpa-include-packages`](https://github.com/redguardtoo/emacs.d/blob/8d5af836f7bed4d3b7f0159a2381fc2e16d9f02b/lisp/init-elpa.el#L54).
