### ISSUE TITLE
Wrong repository language detection.

### ISSUE THREAD

**Issue by proofit404** [redguardtoo/mastering-emacs-in-one-year-guide#58]
Hello.
Github detect that this repository is written in the Common Lisp. I suppose this is because of used `#+BEGIN_SRC lisp` and similar definitions in the Org mode files. Can you try to fix this?

It doesn't really a problem with your project. But it annoying when irrelevant project appears in the top of search result in the different language.

Thanks.
Regards, Artem.

**Comment by redguardtoo** [comment]
How to fix

**Comment by proofit404** [comment]
You can try following:

* Start org-mode code blocks with `#+BEGIN_SRC emacs-lisp` 
* Use `;; -*- Emacs-Lisp -*-` prop line major mode

**Comment by proofit404** [comment]
Thank you.
