### ISSUE TITLE
Gnus 能否通过 socks5 翻墙呢？

### ISSUE THREAD

**Issue by dsdshcym** [redguardtoo/mastering-emacs-in-one-year-guide#59]
设置 Gnus 来接收 Gmail ，第一次成功接收到了，但是之后都很难收到。

能否通过设置用 socks5 代理翻墙呢？

**Comment by redguardtoo** [comment]
good question,http://alexborisov.org/tunnel-your-apps-via-ssh-with-tsocks/, then start emacs in shell with cli `http_proxy=http://127.0.0.1:8000`

**Comment by dsdshcym** [comment]
@redguardtoo 谢谢回复！

我用的是 proxychains-ng ，还没有用过 tsocks ，但是看了你分享的链接后我觉得两个应该是差不多的。

但是使用了 proxychains-ng 打开 emacs 后还是会遇到接收不到的问题，也许是我的翻墙服务不稳定。

Thanks for your reply anyway!

**Comment by redguardtoo** [comment]
Yes, have you tried digitalocean or amazon ec2?

**Comment by dsdshcym** [comment]
@redguardtoo 
找到原因了，在 Mac 上使用 `proxychains4 open -a Emacs` 无法使用代理，而用 `proxychains4 /path-to-Emacs.app/Contents/MacOS/Emacs` 就能通过代理访问了

但是可能在升级系统后无法用后一种方法打开 Emacs ，正在找原因

**Comment by redguardtoo** [comment]
what about tsocks

**Comment by dsdshcym** [comment]
@redguardtoo 
用你在知乎上说的
```sh
export https_proxy=127.0.0.1:7777
export http_proxy=127.0.0.1:7777
./Emacs
```
就可以了

**Comment by autosquid** [comment]
@dsdshcym  这样不就是 https_proxy 了？ 那socks5的设置怎么弄呢？

**Comment by dsdshcym** [comment]
@autosquid  我把 Socks5 转成本地 http 代理服务器了

**Comment by CodeFalling** [comment]
@autosquid 
```
(setq url-gateway-method 'socks)
(setq socks-server '("Default server" "127.0.0.1" 1080 5))
```
Works for `package`,but I don't know dose it work for gnus.

**Comment by redguardtoo** [comment]
interesting, thanks.
