### ISSUE TITLE
why didn't gnus save authinfo to .authinfo.gpg?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/mastering-emacs-in-one-year-guide#66]
i try your .gnus.el and find authinfo is going to save at .authinfo without encryption. is there any setting i should do with my gpg or emacs? i use your .emacs.d

**Comment by redguardtoo** [comment]
Use `.authinfo.gpg`, remove `.authinfo`, if you check my guide, I always say `.authinfo.gpg`

`.authinfo` take priority if it exists, You can get this info by `C-h v auth-sources` (I mentioned in my guide).

**Comment by smallst** [comment]
oh , i just checked Gnus Encrypted AuthInfo in emacswiki and found it..
 i used to think emacs would save file in gpg automated. 
it's my own fault, sorry to bother you.
