### ISSUE TITLE
defadvice

### ISSUE THREAD

**Issue by luoenzhen** [redguardtoo/mastering-emacs-in-one-year-guide#67]
> ﻿﻿Emacs Lisp 书籍推荐(可选)
> 
> Bob Glickstein的Writing GNU Emacs Extensions是最好的.
> 
> 生动,例子丰富.作者用心安排了书的结构.例如,很早就介绍了defadvice的用法.defadvice 是Emacs Lisp的精华.

please note that defadvice is deprecated and people should now use add-function, add-advice

**Comment by redguardtoo** [comment]
Yes. maybe we should use add-function instead. Are u still using python?

**Comment by luoenzhen** [comment]
Python时不时的会用一下。

**Comment by redguardtoo** [comment]
spacemacs is the most popular setup now.  It supports python and all other languages.
My own setup focus on more javascript/html/css, but do have OK python support though I never got a chance to write python in Australia ;(

What your major language? js?

**Comment by luoenzhen** [comment]
js will be dead in short future. emacs won't.

**Comment by redguardtoo** [comment]
can't agree more.
