### ISSUE TITLE
org-mode模式中表格中英文混排对齐的问题

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/mastering-emacs-in-one-year-guide#71]
org-mode模式中，表格中如果中英文混排的话，总是对不齐，就像下面这样：
![3](https://cloud.githubusercontent.com/assets/16398130/14974239/e64c9a10-1124-11e6-842b-51884201093a.png)
按照[这里](http://coldnew.github.io/blog/2013/11-16_d2f3a/)的方法，但是没有效果。函数可以调用，但似乎被屏蔽了。

关于中英文混排，能给我一些建议吗？

**Comment by redguardtoo** [comment]
fixed width font

**Comment by tumashu** [comment]
chinese-fonts-setup 专门解决这事的扩展
