### ISSUE TITLE
gtags ignore function declaration without definition

### ISSUE THREAD

**Issue by paulinus1988** [redguardtoo/mastering-emacs-in-one-year-guide#72]
same as [the problem](https://lists.gnu.org/archive/html/help-global/2011-09/msg00004.html) 
I have some header files(.h) where function declared without definistion. And I get no sources, But I really need tags can help me with finding the declaration(ex: M+.).
Or do you have any good ideas about locating func declaration in redguardtoo`s emacs conf.
Really thanking you

**Comment by redguardtoo** [comment]
GTAGSFORCECPP

**Comment by paulinus1988** [comment]
```
paulinus:~/test$ export GTAGSFORCECPP=

paulinus:~/test$ gtags .

paulinus:~/test$ ls
GPATH  GRTAGS  GTAGS  test.h

paulinus:~/test$ global a

paulinus:~/test$ global b
test.h

paulinus:~/test$ cat test.h
int a();
int b(){
};

```

GTAGSFORCECPP does not work

**Comment by redguardtoo** [comment]
`export GTAGSFORCECPP=""`

**Comment by paulinus1988** [comment]
thx a lot. It seems that using gtags as backend of language auto complete is not a good idear when only having c hearders. I need to find another way. Could you help pointing me out?

**Comment by redguardtoo** [comment]
company-clang

**Comment by paulinus1988** [comment]
thanks a lot.
