### ISSUE TITLE
关于配置的缩进问题

### ISSUE THREAD

**Issue by huddy1985** [redguardtoo/mastering-emacs-in-one-year-guide#73]
你好，非常感谢分享的配置，现在在逐渐熟悉emacs中，
该过程中发现一个问题：
我的操作模式在c-mode下，当我输入一行代码：
if(xxx == yyy)
在这里，如果我上面没有加{的话，该处的缩进就跟if对齐了，这样
if (xxx == yyy)
aaa();
能否将该处修正呢？就是不需要{}也能使if下面一行的缩进一个tab，谢谢。

from Xuguo Wang
mail: huddy1985@gmail.com

**Comment by mistkafka** [comment]
我有一个不成熟的小建议，还是写{}，即使这个if的body为空。**据说**这是最佳实践......[这个](https://www.emacswiki.org/emacs/IndentingC)可能能帮到你。

**Comment by redguardtoo** [comment]
comment out `(fix-c-indent-offset-according-to-syntax-context 'substatement 0)` in init-cc-mode.el

But then if you want to write code,
```c
if(1)
{
}
```
The first `{` will always indent 4 spaces. That's annoying for other C developers. Anyway, your choice. `C-h v c-offsets-alist` for more details.

**Comment by huddy1985** [comment]
Perfect, it works, thank you redguardtoo.. And all.
