### ISSUE TITLE
org-mode中的网页链接问题

### ISSUE THREAD

**Issue by 734986860hf** [redguardtoo/mastering-emacs-in-one-year-guide#76]
你好,我的emacs版本24.4,使用的您的配置,但是我发现我在org-mode中点击网页链接时,提示我
 Install w3m command in `exec-path' or set`w3m-command' variable correctly,
但是我已经把browse-url设置为我的默认浏览器了,

P.S.请问org-mode中是根据什么来选择其打开链接的,在哪设置？

**Comment by redguardtoo** [comment]
It's decided by variable `browse-url-browser-function`, in init-org.el , I adviced `org-open-at-point`, you can `C-u org-open-at-point` to open link with external browser.

**Comment by 734986860hf** [comment]
I open the init-org.el and I find these lines and I try to alter it

                (lambda (url &optional new)
                  (browse-url url t))))))
    ad-do-it))
but it didn't work，why? browse-url  ??Symbol's function definition is void

**Comment by 734986860hf** [comment]
thank you,i alter the  (lambda (url &optional new)
                  ( browse-url-default-windows-browser url t))
so the c-c c-o can open my default browser，but when i alter it to he browse-url it don't work again

**Comment by 734986860hf** [comment]
thank you,i alter the  (lambda (url &optional new)
                  ( browse-url-default-windows-browser url t))
so the c-c c-o can open my default browser，but when i alter it to he browse-url it don't work again

the error is browse-url: Variable binding depth exceeds max-specpdl-size

**Comment by redguardtoo** [comment]
Obviously should be browser-url-generic  instead of `browse-url-default-windows-browser` which doesn't exist in my setup.

**Comment by 734986860hf** [comment]
(setq browse-url-browser-function 'browse-url-generic
      browse-url-generic-program "firefox-browser") is not working for me

which in the init-org is                 (lambda (url &optional new)
                  ( browse-url-generic url t))

**Comment by redguardtoo** [comment]
browse-url-generic-program's value is "/usr/bin/firefox" on my machine

**Comment by 734986860hf** [comment]
Thank you for your reply，when I change my system from win to ubuntu，everything is fine

**Comment by redguardtoo** [comment]
You can use it on windows, assign firefox or chrome to `browse-url-generic-program` and add browser's directory to environment variable PATH

**Comment by 734986860hf** [comment]
I have the directory to PATH,so I can see "C:/Program Files (x86)/Mozilla Firefox"  When I press M-x getenv RET PATH, But,


(setq browse-url-browser-function 'browse-url-generic
browse-url-generic-program "firefox-browser")  isn't work at all 

when i click the link 
browse-url-generic: No browser defined (`browse-url-generic-program')

**Comment by redguardtoo** [comment]
firefox-browser.exe exist？

**Comment by 734986860hf** [comment]
firefox.exe is in the folder,but i also used browse-url-generic-program "firefox",it isn't work

**Comment by redguardtoo** [comment]
firefox.exe should exist, it's directory should be added into environment variable `PATH`

**Comment by 734986860hf** [comment]
of course it in the PATH when i M-X getenv i see it
