### ISSUE TITLE
Multiple accounts on same server

### ISSUE THREAD

**Issue by pmatos** [redguardtoo/mastering-emacs-in-one-year-guide#77]
You mention:

>  Please note the multiple accounts at the same mail server is troublesome. Don’t waste time on it.

However this tutorial explains it how to achieve it with relative ease. Maybe you can link to it:
http://www.cataclysmicmutation.com/2010/11/multiple-gmail-accounts-in-gnus

**Comment by redguardtoo** [comment]
Thanks.

**Comment by FrancescElies** [comment]
Hi,
I was also interested on that, I tried [cataclysmicmutation](http://www.cataclysmicmutation.com/2010/11/multiple-gmail-accounts-in-gnus)  no success, somehow I could not manage.
I actually found interesting [cataclysmicmutation](http://www.cataclysmicmutation.com/2010/11/multiple-gmail-accounts-in-gnus) didn't have to add each folder to the `gnus-topic-alist` but used regex instead. I could not manage this one neither
 
@pmatos if you could provide a link with an example of a working `.gnus.el` file it would be awesome.

In the end I did a terrible hack to solve that issue by adding the following line to you `/etc/hosts` file 

`64.233.166.108  work.imap.gmail.com`

That ip corresponds to `imap.gmail.com`

Afterwards I followed @redguardtoo `.gnus.el` example and added
```
(add-to-list 'gnus-secondary-select-methods
             '(nnimap "gmail-work" ; key
                      (nnimap-address "work.imap.gmail.com")
                      (nnimap-server-port 993)
                      (nnimap-stream ssl)
                      (nnir-search-engine imap)
                      ;; @see http://www.gnu.org/software/emacs/manual/html_node/gnus/Expiring-Mail.html
                      ;; press 'E' to expire email
                      (nnmail-expiry-target "nnimap+gmail-work:[Gmail]/Trash")
                      (nnmail-expiry-wait 90)))
```
In any case, thanks for your time and this tutorials

**Comment by redguardtoo** [comment]
@ FrancescElies 

For gnus-topic, you can use vim or cua-mode to edit the mail folders. That's pretty quick.

**Comment by FrancescElies** [comment]
Thanks for the tip
