### ISSUE TITLE
Gnus to maintain the HTML structure of the original email during replies?

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#78]
I am using Gnus in organization/team where 99% people are using MS Outlook. Gnus provides a way to send HTML email (compose or reply to). However, especially while replying to the email, it doesn't preserve the HTML formatting of the earlier messages in the thread. This irritates other people whom I interact with. Do you face similar issues? How do you overcome them?

I am using Gnus outlook style package (https://github.com/lokedhs/gnus-outlook-style). However, it has few issues and limitations (especially you can't inline edit older messages).

**Comment by redguardtoo** [comment]
A interesting question.

As you know from my guide, you can always write plain text and use `org-mime-htmlize` to convert YOUR text to html.

If you want to quote the sender's html mail, you can press =e= or `M-x gnus-summary-edit-article` to view the raw html of the mail. It's a simple copy/paste job.

**Comment by amittendulkar** [comment]
Thanks. The above solution should work for me.
