### ISSUE TITLE
some doubts from gnus

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/mastering-emacs-in-one-year-guide#79]
## first

`M-x gnus`
it prompt import my imap name and pwd for gmail
when restart emacs it prompts again
## second

run into gnus

> warming message
> Warning: Opening nnimap server on gmail...failed: NO (AUTHENTICATIONFAILED) Invalid credentials (Failure); Server nnimap+gmail previously determined to be down; not retrying; Opening nnimap server on gmail...failed: NO (AUTHENTICATIONFAILED) Invalid credentials (Failure)  
## third

the gmane nntp server is down 
if any good emacs server like planet.emacsen replace?

**Comment by redguardtoo** [comment]
1. Yes. That's normal. Read my gnus guide.
2. Should not happen, check my gnus guide
3. I don't use gmane, but as I check its wiki, it's shut down now, wiki list some alternatives. https://en.wikipedia.org/wiki/Gmane

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
## fourth
the init-bbdb.el is merged in .gnus.el?

**Comment by redguardtoo** [comment]
.gnus.el is my private file. init-bbdb.el is shared to the public

My gnus guide is in this project.
