### ISSUE TITLE
org 中直接 display 外链图片

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/mastering-emacs-in-one-year-guide#81]
the link of 图片   file:~/desktop/Git_Flow.png
use many way to 显示都不行
例: 
1. M-x org-toggle-inline-images
2. M-x image-mode
3. M-x dispaly-inline-images

**Comment by redguardtoo** [comment]
I don't know. I never use this feature, but I tried googling, http://stackoverflow.com/questions/17621495/emacs-org-display-inline-images

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
thanks for it
but it 仍然显示 in buffer-menu
> No images to display inline

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
the path is should be 
[[file:~/desktop/Git_Flow.png]]
### egg pain
