### ISSUE TITLE
为什么C-n有的时候好用（切换到下一行，有的时候不好用，切换不了）

### ISSUE THREAD

**Issue by guyanf** [redguardtoo/mastering-emacs-in-one-year-guide#85]
今天刚开始使用您的配置，确实挺好的，但是在使用过程中，emacs原有的很多快捷键在新的配置下，有的时候可以用，有的时候不行（应该是我的个人使用问题，不应该是您的配置文件的问题），我不知道是什么原因，请指导，谢谢！

现在我按下C-n，想切换下一行，实际并没有切换，下方提示：
Previous command was not an evil-paste:evil-paste-pop

**Comment by redguardtoo** [comment]
If you disable evil-mode completely (check README). Then `C-n` is always next line.

Or else, you are using evil-mode (vim emulator), so you are using vim key bindings.

**Comment by guyanf** [comment]
Thanks！
