### ISSUE TITLE
Suggestion for using Gmail syntax for search

### ISSUE THREAD

**Issue by rhashimoto** [redguardtoo/mastering-emacs-in-one-year-guide#87]
Instead of using `C-u G G` for search by field or with the IMAP syntax, you can instead configure a new IMAP search mode for [Gmail syntax](https://support.google.com/mail/answer/7190?hl=en) and make that the default:

```
(add-to-list 'nnir-imap-search-arguments '("gmail" . "X-GM-RAW"))
(setq nnir-imap-default-search-key "gmail")
```

The advantage of this is that you can use the unprefixed `G G` both to search entire messages (by entering plain search words, just as before), and to specify more complicated searches with the Gmail options. It is easier to type `G G from:foo <RETURN>` than `C-u G G foo <RETURN> from <RETURN>`, plus the search history is more useful for repeating or modifying past searches.

The IMAP syntax does have `HEADER <field-name> <string>` to search messages based on header content, which the Gmail syntax does not support. The Gmail syntax has better support for searching for Gmail-specific concepts (e.g. `is:starred`, `is:important`), and for searching for attachments by name or type (e.g. `file:pdf`, `file:agenda`). On balance I find the Gmail syntax more useful (and you can still use `C-u G G` for IMAP syntax if desired).

**Comment by redguardtoo** [comment]
Cool. Let me try it.

**Comment by redguardtoo** [comment]
23bd3ea search mail by gmail search syntax (Chen Bin)
