### ISSUE TITLE
 无法归类 Gnus Group Topics

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/mastering-emacs-in-one-year-guide#88]
按照博主的指导 http://blog.binchen.org/posts/how-to-use-gnus-group-topics-efficiently.html

最后得到这么一个奇怪的东西(gmail)

<img width="292" alt="2016-11-23 9 01 55" src="https://cloud.githubusercontent.com/assets/16307328/20562730/1aa6996e-b1c0-11e6-87d6-b369cebda4fd.png">

**Comment by redguardtoo** [comment]
read my gnus guide where I said by default Gnus will NOT display mails you already read.
