### ISSUE TITLE
emacs配置后，软件的错误提示时软件中央出现黑色方块

### ISSUE THREAD

**Issue by russellfei** [redguardtoo/mastering-emacs-in-one-year-guide#9]
mac 10.9 ＋ GNU Emacs 24.3
使用的时博主的配置，自己去掉了evil扩展
相应的第三方库是让emacs启动时自行下载编译的。
问题如下：
1. 启动时原先是带有颜色主题的界面，但是是默认大窗体。
我想改称此前默认的80x24，查过有关设置default-frame-alist的命令，请问放哪里合适？
2. 设置鼠标滚动无效后，双指滑动时有错误提示，并在窗体
中央出现黑色方块。（图片不知原因无法贴出来T_T）
3. Meta键绑定在了Super上，emacs里面M-v无法使用了。
虽然在osx-key中设置了适应mac系统的按键，但是M-v无法翻页比其他的功能重要。
谢谢大家的帮助～

**Comment by Jamsa** [comment]
(setq visible-bell nil)
关闭后我的没有出现黑框了

**Comment by redguardtoo** [comment]
谢谢，我改了visible bell的设置。
