### ISSUE TITLE
About Conkeror Web Browser 

### ISSUE THREAD

**Issue by LdBeth** [redguardtoo/mastering-emacs-in-one-year-guide#94]
[Conkeror](https://conkeror.org) is a light weight web browser based on Mozilla's XULRunner. 

Similar to Keysnail, it provides a Emacs like interface. 
I think it can be a good alternative choice. I just wonder if you have tried this,
and if not, it is worth to have a try.

Some tips: now the XULRunner is obsoleted and doesn't support recent 
versions of macOS , but it works when building with latest FireFox

**Comment by redguardtoo** [comment]
I use Conkeror several years ago. Don't remember why I choose keysnail. Maybe because I have to use firefox on Windows? I will find some time to re-evaluate Conkeror soon.
