### ISSUE TITLE
关于C语言那部分，我该如何启用？

### ISSUE THREAD

**Issue by YuanPres** [redguardtoo/mastering-emacs-in-one-year-guide#95]
我现在在使用 Steve Purcell 的配置。
我确定我的Clang和company-clang已经安装，但是我仍然不知道该添加什么代码以启用。并且我希望能在不破坏他的工程结构的前提下完成。
求指教，谢谢！

**Comment by redguardtoo** [comment]
Use ctags is good enough. You need setup `tags-table-list`. company should works out of box

**Comment by YuanPres** [comment]
Thanks
