### ISSUE TITLE
Using org-mime-htmlize in message buffer converting text after underscore to subscript

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#97]
I am using Emacs 24.5.1 on Ubuntu 16.04.2. While editing email in Gnus message buffer to HTML, I see that the text with underscore is converted to subscript in HTML. I did `C-h v org-sub-superscripts` and ensured that the variable value is `{}`.

What must be wrong? Pasting the exact text displayed in help for reference,
```
org-use-sub-superscripts is a variable defined in `org.el'.
Its value is {}
Original value was t
```

**Comment by redguardtoo** [comment]
Don't know you setup. I'm using Emacs 25.1.
After `C-h v org-use-sub-superscripts`, it says,
```info
If you want to control how Org exports those characters, see
‘org-export-with-sub-superscripts’.  ‘org-use-sub-superscripts’
used to be an alias for ‘org-export-with-sub-superscripts’ in
Org <8.0, it is not anymore.
```

`(setq org-export-with-sub-superscripts '{})` works.

**Comment by amittendulkar** [comment]
Thanks. My bad. I missed reading the message regarding the export.
