### ISSUE TITLE
Not able to input '<' character in message buffer

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#98]
I am not able to input a `<` character while composing email or putting TO/CC addresses in Gnus message buffer. It seems `<` is bound to some command. Can you please comment?

Emacs 24.5.1 on Ubuntu 16.04.2. I am using your `.emacs.d` (mostly around 2 months old)

**Comment by redguardtoo** [comment]
3c497d5 clean bbdb setup (Chen Bin)

**Comment by amittendulkar** [comment]
I upgraded my Emacs to 25.1 and also did git pull of your .emacs.d. But the issue didn't get resolved? Do I need to clean BBDB setup (how?)?

**Comment by redguardtoo** [comment]
If there is a line `(local-set-key (kbd "TAB") 'bbdb-complete-name))` in `init-bbdb.el`, then you are using the latest version. I tested with `emacs 25.1.1`

Or you can delete that line.

**Comment by amittendulkar** [comment]
I have deleted the line containing `bbdb-complete-name`. However I am still facing the same issue. I tried searching for `bbdb-complete-name` call across files in my .emacs.d but couldn't find them.

```
~/.emacs.d$ grep -r "bbdb-complete-name" *
elpa/bbdb-20151114.1541/bbdb-com.el:(define-obsolete-function-alias 'bbdb-complete-name 'bbdb-complete-mail)
elpa/bbdb-20151114.1541/bbdb-autoloads.el:(define-obsolete-function-alias 'bbdb-complete-name 'bbdb-complete-mail)
Binary file elpa/bbdb-20151114.1541/bbdb-com.elc matches
lisp/init-bbdb.el:  ;; (local-set-key (kbd "TAB") 'bbdb-complete-name)
lisp/init-bbdb.el:   bbdb-complete-name-allow-cycling t       ;; cycle through matches
```

**Comment by redguardtoo** [comment]
tested with both 24.5.1 and 25.1, can't reproduce the issue.

If you are sure it's my setup, 
- clone my setup
- use `git bisect` to find the commit. See https://git-scm.com/docs/git-bisect

**Comment by amittendulkar** [comment]
Okay. However, I am not sure whether there was a stage where `<` input character was working for me. How to handle the situation in `git bisect` where I don't know whether good commit level exists? Probably I will need to keep going back to older versions in 6-months time slots till I see a starting point of good version.

**Comment by redguardtoo** [comment]
Yes, six months should be OK.
