### ISSUE TITLE
Gnus: Coloring of email reply history disappeared after taking update of .emacs.d

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/mastering-emacs-in-one-year-guide#99]
In my earlier .emacs.d setup (Emacs 24.5), the Gnus had a useful feature where it used to color the text differently if the HTML message text was in different color. It helped my identify inline responses sent by Outlook users.

With the latest .emacs.d (and Emacs 25.1) the above feature has disappeared. What can I do to enable it?

**Comment by redguardtoo** [comment]
Could you show me some example and screenshot?

I don't override the Gnus default setup.

**Comment by amittendulkar** [comment]
Here is a small snapshot of the email message where the green text is the inline edit by other person. This text highlighting is no more happening in latest .emacs.d
![image](https://user-images.githubusercontent.com/18111340/27063922-26a8331c-5012-11e7-9578-07c11c7fcf99.png)

**Comment by redguardtoo** [comment]
Check my gnus guide, I always use w3m to render the html mail. But emacs maintainers keep changing the default html rendering engine (w3m -> shr -> ewws) which I don't like.

**Comment by amittendulkar** [comment]
I am using w3m for email rendering. This is from your older init-emacs-w3m.el
```
(setq w3m-coding-system 'utf-8
      w3m-file-coding-system 'utf-8
      w3m-file-name-coding-system 'utf-8
      w3m-input-coding-system 'utf-8
      w3m-output-coding-system 'utf-8
      ;; emacs-w3m will test the ImageMagick support for png32
      ;; and create files named "png32:-" everywhere
      w3m-imagick-convert-program nil
      w3m-terminal-coding-system 'utf-8
      w3m-use-cookies t
      w3m-cookie-accept-bad-cookies t
      w3m-home-page "http://www.google.com.au"
      w3m-command-arguments       '("-F" "-cookie")
      w3m-mailto-url-function     'compose-mail
      browse-url-browser-function 'w3m
      ;; use shr to view html mail, but if libxml NOT available
      ;; use w3m isntead. That's Emacs 24.3+ default logic
      ;; mm-text-html-renderer 'shr
      w3m-use-toolbar t
      ;; show images in the browser
      ;; setq w3m-default-display-inline-images t
      ;; w3m-use-tab     nil
      w3m-confirm-leaving-secure-page nil
      w3m-search-default-engine "g"
      w3m-key-binding 'info)
```

**Comment by amittendulkar** [comment]
Meanwhile the rendering changed slightly (from the way I used to see it) after I copied the .emacs.d from my Windows drive to GNU/Linux. Not sure why.

**Comment by amittendulkar** [comment]
I am seeing the above code in your latest .emacs.d as well. `.gnus.el` is the same in both cases. I am assuming that the HTML rendering engine is still w3m.

**Comment by amittendulkar** [comment]
Here is `C-h v mm-text-html-renderer` is showing,

```
mm-text-html-renderer is a variable defined in ‘mm-decode.el’.
Its value is ‘w3m’
Original value was shr

Documentation:
Render of HTML contents.
It is one of defined renderer types, or a rendering function.
The defined renderer types are:
‘shr’: use the built-in Gnus HTML renderer;
‘gnus-w3m’: use Gnus renderer based on w3m;
‘w3m’: use emacs-w3m;
‘w3m-standalone’: use plain w3m;
‘links’: use links;
‘lynx’: use lynx;
‘html2text’: use html2text;
nil    : use external viewer (default web browser).
```

**Comment by redguardtoo** [comment]
`M-x current-font-face` on the highlighted text, besides, could you create a step by step sample?

**Comment by amittendulkar** [comment]
Getting the following in older .emacs.d (where Gnus is rendering correctly).
`(variable-pitch (:foreground "#00B050")) => clipboard & yank ring`
Getting the following in latest .emacs.d (where Gnus is not rendering correctly).
`nil => clipboard & yank ring`

Here are the steps. I opened Outlook 365 Web UI and composed the following email to send to my gmail address (captured from the Sent Items folder in Outlook 365 Web UI).
![image](https://user-images.githubusercontent.com/18111340/27069820-1bec2e20-5034-11e7-9a5e-a00168391249.png)

In the Gnus with newer .emacs.d I am seeing the email in the following way (no colors).
![image](https://user-images.githubusercontent.com/18111340/27069868-4572068e-5034-11e7-99b2-f1d74d0dbad1.png)

The `M-x current-font-face` is showing `nil`.

I switch to Gnus with older .emacs.d and seeing the following (with colors),
![image](https://user-images.githubusercontent.com/18111340/27070002-c07fa8ea-5034-11e7-9c66-84e78ae4a72b.png)

Got following for `M-x current-font-face` (selected small region with green text),
`(variable-pitch (:foreground "#49a422") (:background "#fffeff") (:foreground "#000000") (:background "#FFFFFF") (:foreground "#000000") (:background "#00FF00") (:foreground "#787878")) => clipboard & yank ring`

**Comment by redguardtoo** [comment]
I restored the default engine `shr`, see b3d666b let user decide html rendering engine (Chen Bin)

You can still use `w3m` by setup in `.gnus.el`.
